### ISSUE TITLE
Criação do registro de Transferencia

### ISSUE THREAD

**Issue by hav0kinho** [Pl4y3rOn3/SCM_Psicultura#3]
import sequelize, { Deferrable, HasOne } from "sequelize";
import Povoamento from "./Povoamento";
import Viveiro from "./Viveiro";
const db = require("../db/db");

const Transferencia = db.define("transferencia", {
  tokenTransferencia: {
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
    type: sequelize.INTEGER,
  },
  povoamento: {
    allowNull: false,
    type: sequelize.CHAR(30),
    references: {
      model: Povoamento,
      key: 'idPovoamento',
      deferrable: Deferrable.INITIALLY_IMMEDIATE
    },
  },
  viveiro: {
    allowNull: false,
    type: sequelize.CHAR(30),
    references: {
      model: Viveiro,
      key: 'idViveiro',
      deferrable: Deferrable.INITIALLY_IMMEDIATE
    },
  },
  quantidadepovoada: {
    allowNull: false,
    type: sequelize.INTEGER,
    validate:{min:0},
  },
});

Transferencia.sync();

export default Transferencia;

**Comment by Pl4y3rOn3** [comment]
Resolvido
